/**
 * Hand-written DB types that mirror the Supabase schema.
 * In a real project these would be generated by `supabase gen types typescript`.
 */

export type BookingStatus = "pending" | "confirmed" | "cancelled" | "completed";

export interface Coach {
  id: string;
  user_id: string;
  email: string;
  full_name: string;
  bio: string | null;
  hourly_rate: number | null;
  lat: number | null;
  lng: number | null;
  zip: string | null;
  sport: string | null;
  photo_url: string | null;
  stripe_account_id: string | null;
  onboarding_complete: boolean;
  created_at: string;
  updated_at: string;
}

export interface Player {
  id: string;
  user_id: string;
  email: string;
  full_name: string;
  skill_level: string | null;
  sport: string | null;
  created_at: string;
  updated_at: string;
}

export interface AvailabilitySlot {
  id: string;
  coach_id: string;
  /** Concrete start datetime (non-recurring bookable slots). Nullable for recurring templates. */
  slot_start: string | null;
  /** Concrete end datetime (non-recurring bookable slots). Nullable for recurring templates. */
  slot_end: string | null;
  is_booked: boolean;
  /** 0 = Sunday … 6 = Saturday (recurring slots only) */
  day_of_week: number | null;
  /** HH:MM (24-hour) — recurring slots only */
  start_time: string | null;
  /** HH:MM (24-hour) — recurring slots only */
  end_time: string | null;
  is_recurring: boolean;
  created_at: string;
  updated_at: string;
}

/** A recurring weekly availability template row */
export interface RecurringSlot {
  id: string;
  coach_id: string;
  day_of_week: number;   // 0–6
  start_time: string;    // "HH:MM"
  end_time: string;      // "HH:MM"
}

/** An open booking window derived from recurring availability (concrete date + time) */
export interface OpenSlot {
  date: string;           // "YYYY-MM-DD"
  start_time: string;     // "HH:MM"
  end_time: string;       // "HH:MM"
  start_datetime: string; // ISO string (for booking / display)
  end_datetime: string;   // ISO string (for booking)
}

export interface Booking {
  id: string;
  coach_id: string;
  player_id: string | null;           // null for guest (no-account) checkouts
  availability_slot_id: string | null;
  slot_start: string;
  slot_end: string;
  status: BookingStatus;
  hourly_rate: number;
  stripe_payment_intent_id: string | null;
  stripe_checkout_session_id: string | null;
  guest_name: string | null;
  guest_email: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface Database {
  public: {
    Tables: {
      coaches: {
        Row: Coach;
        Insert: Omit<Coach, "id" | "created_at" | "updated_at" | "onboarding_complete"> & {
          id?: string;
          onboarding_complete?: boolean;
        };
        Update: Partial<Omit<Coach, "id" | "created_at">>;
      };
      players: {
        Row: Player;
        Insert: Omit<Player, "id" | "created_at" | "updated_at"> & { id?: string };
        Update: Partial<Omit<Player, "id" | "created_at">>;
      };
      availability_slots: {
        Row: AvailabilitySlot;
        Insert: Omit<AvailabilitySlot, "id" | "created_at" | "updated_at"> & {
          id?: string;
          is_booked?: boolean;
          is_recurring?: boolean;
        };
        Update: Partial<Omit<AvailabilitySlot, "id" | "created_at">>;
      };
      bookings: {
        Row: Booking;
        Insert: Omit<Booking, "id" | "created_at" | "updated_at"> & {
          id?: string;
          status?: BookingStatus;
        };
        Update: Partial<Omit<Booking, "id" | "created_at">>;
      };
    };
  };
}
