/**
 * Hand-written DB types that mirror the Supabase schema.
 * In a real project these would be generated by `supabase gen types typescript`.
 */

export type BookingStatus = "pending" | "confirmed" | "cancelled" | "completed";

export interface Coach {
  id: string;
  user_id: string;
  email: string;
  full_name: string;
  bio: string | null;
  hourly_rate: number | null;
  lat: number | null;
  lng: number | null;
  zip: string | null;
  sport: string | null;
  onboarding_complete: boolean;
  created_at: string;
  updated_at: string;
}

export interface Player {
  id: string;
  user_id: string;
  email: string;
  full_name: string;
  skill_level: string | null;
  sport: string | null;
  created_at: string;
  updated_at: string;
}

export interface AvailabilitySlot {
  id: string;
  coach_id: string;
  slot_start: string;
  slot_end: string;
  is_booked: boolean;
  created_at: string;
  updated_at: string;
}

export interface Booking {
  id: string;
  coach_id: string;
  player_id: string;
  availability_slot_id: string | null;
  slot_start: string;
  slot_end: string;
  status: BookingStatus;
  hourly_rate: number;
  stripe_payment_intent_id: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface Database {
  public: {
    Tables: {
      coaches: {
        Row: Coach;
        Insert: Omit<Coach, "id" | "created_at" | "updated_at" | "onboarding_complete"> & {
          id?: string;
          onboarding_complete?: boolean;
        };
        Update: Partial<Omit<Coach, "id" | "created_at">>;
      };
      players: {
        Row: Player;
        Insert: Omit<Player, "id" | "created_at" | "updated_at"> & { id?: string };
        Update: Partial<Omit<Player, "id" | "created_at">>;
      };
      availability_slots: {
        Row: AvailabilitySlot;
        Insert: Omit<AvailabilitySlot, "id" | "created_at" | "updated_at"> & {
          id?: string;
          is_booked?: boolean;
        };
        Update: Partial<Omit<AvailabilitySlot, "id" | "created_at">>;
      };
      bookings: {
        Row: Booking;
        Insert: Omit<Booking, "id" | "created_at" | "updated_at"> & {
          id?: string;
          status?: BookingStatus;
        };
        Update: Partial<Omit<Booking, "id" | "created_at">>;
      };
    };
  };
}
