/**
 * ChatBubbles.tsx
 *
 * Presentational components for the AI coach chat interface.
 *
 * - AssistantBubble: renders the coach's replies with full markdown formatting
 *   (bold, italic, bullet/numbered lists, code, headings) via markdown-to-jsx.
 * - UserBubble: renders the user's own messages as plain text (no markdown).
 * - TypingIndicator: animated dots shown while the assistant is typing.
 *
 * Splitting these out of ChatClient.tsx keeps the markdown logic isolated and
 * makes the components straightforward to unit-test.
 */

import Markdown from "markdown-to-jsx";

// ── TypingIndicator ───────────────────────────────────────────────────────────

export function TypingIndicator() {
  return (
    <div
      className="flex items-center gap-1 px-1 py-1"
      aria-label="Coach is typing"
    >
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          className="inline-block w-2 h-2 rounded-full bg-slate-500 animate-bounce"
          style={{ animationDelay: `${i * 150}ms` }}
        />
      ))}
    </div>
  );
}

// ── Markdown rendering options ────────────────────────────────────────────────

/**
 * Override each HTML element generated by markdown-to-jsx so Tailwind classes
 * style them within the slate-800 bubble correctly.
 *
 * We do NOT enable raw HTML (dangerouslySetInnerHTML) — markdown-to-jsx strips
 * any raw HTML from AI-generated content, which is the safe default.
 */
const markdownOptions: React.ComponentProps<typeof Markdown>["options"] = {
  overrides: {
    p: {
      props: { className: "mb-2 last:mb-0" },
    },
    strong: {
      props: { className: "font-semibold text-white" },
    },
    em: {
      props: { className: "italic" },
    },
    ul: {
      props: {
        className: "list-disc list-outside pl-5 mb-2 space-y-0.5",
      },
    },
    ol: {
      props: {
        className: "list-decimal list-outside pl-5 mb-2 space-y-0.5",
      },
    },
    li: {
      props: { className: "leading-relaxed" },
    },
    code: {
      props: {
        className:
          "bg-slate-700 rounded px-1 py-0.5 text-xs font-mono break-all",
      },
    },
    pre: {
      props: {
        className: "bg-slate-700 rounded p-3 text-xs font-mono overflow-x-auto mb-2",
      },
    },
    h1: {
      props: { className: "text-base font-bold text-white mb-2 mt-1" },
    },
    h2: {
      props: { className: "text-sm font-bold text-white mb-1.5 mt-1" },
    },
    h3: {
      props: { className: "text-sm font-semibold text-white mb-1 mt-1" },
    },
    hr: {
      props: { className: "border-slate-600 my-2" },
    },
    blockquote: {
      props: {
        className:
          "border-l-2 border-slate-500 pl-3 italic text-slate-300 my-2",
      },
    },
  },
};

// ── AssistantBubble ────────────────────────────────────────────────────────────

/**
 * Renders an AI coach message with full markdown formatting.
 *
 * During streaming the component either shows a typing indicator (empty state)
 * or the in-progress content with an animated cursor appended after the last
 * rendered block — markdown-to-jsx re-parses the partial string on each render,
 * so incremental appending works correctly throughout the stream.
 */
export function AssistantBubble({
  content,
  streaming,
}: {
  content: string;
  streaming?: boolean;
}) {
  return (
    <div className="flex justify-start gap-2.5">
      {/* Coach avatar */}
      <div
        className="shrink-0 mt-0.5 w-7 h-7 rounded-full bg-green-800 flex items-center justify-center text-sm"
        aria-hidden="true"
      >
        🎾
      </div>

      <div className="max-w-[80%] rounded-2xl rounded-tl-sm bg-slate-800 border border-slate-700 px-4 py-2.5 text-sm text-slate-100 leading-relaxed shadow-sm">
        {content.length > 0 && (
          <Markdown options={markdownOptions}>{content}</Markdown>
        )}
        {streaming &&
          (content.length === 0 ? (
            <TypingIndicator />
          ) : (
            <span
              className="ml-0.5 inline-block w-0.5 h-4 bg-green-400 animate-pulse align-middle"
              aria-hidden="true"
            />
          ))}
      </div>
    </div>
  );
}

// ── UserBubble ────────────────────────────────────────────────────────────────

/**
 * Renders the user's own message as plain text inside a green bubble.
 * No markdown parsing — user input is displayed verbatim.
 */
export function UserBubble({ content }: { content: string }) {
  return (
    <div className="flex justify-end">
      <div className="max-w-[80%] rounded-2xl rounded-tr-sm bg-green-700 px-4 py-2.5 text-sm text-white leading-relaxed shadow-sm">
        {content}
      </div>
    </div>
  );
}
