-- =============================================================
-- CourtCoach AI – Daily Recommendations
-- Migration: 004_daily_recommendations
-- =============================================================

-- ──────────────────────────────────────────────────────────────
-- daily_recommendations
--
-- One row per (user, date). Generated by Claude Haiku when the
-- dashboard is first loaded each day; subsequent loads return
-- the cached row without a Claude call.
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.daily_recommendations (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                 UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  recommendation_date     DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- All 7 required content keys
  session_goal            TEXT NOT NULL,
  warmup                  TEXT NOT NULL,
  main_block              TEXT NOT NULL,
  secondary_drill         TEXT NOT NULL,
  fitness_note            TEXT NOT NULL,
  mental_focus            TEXT NOT NULL,
  cooldown                TEXT NOT NULL,
  estimated_duration_mins INT  NOT NULL CHECK (estimated_duration_mins > 0),

  -- One row per user per day
  UNIQUE (user_id, recommendation_date)
);

-- Indices
CREATE INDEX IF NOT EXISTS daily_recommendations_user_date_idx
  ON public.daily_recommendations (user_id, recommendation_date DESC);

-- ──────────────────────────────────────────────────────────────
-- Auto-update updated_at
-- ──────────────────────────────────────────────────────────────
CREATE TRIGGER daily_recommendations_updated_at
  BEFORE UPDATE ON public.daily_recommendations
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- ──────────────────────────────────────────────────────────────
-- Row Level Security (RLS)
-- ──────────────────────────────────────────────────────────────
ALTER TABLE public.daily_recommendations ENABLE ROW LEVEL SECURITY;

-- Users can only read their own recommendations
CREATE POLICY "Users can read own recommendations"
  ON public.daily_recommendations
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert only their own recommendations
CREATE POLICY "Users can insert own recommendations"
  ON public.daily_recommendations
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update only their own recommendations (needed for refresh/upsert)
CREATE POLICY "Users can update own recommendations"
  ON public.daily_recommendations
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
